### ISSUE TITLE
[Questiont] Do we need Thorium alongside with Debugify?[Bug] Summary of bug

### ISSUE THREAD

**Issue by ardissaps** [isXander/Debugify#100]
### Bug Description

Should install both?

### Version

Latest

### Mod Loader Version

Latest

### Mod Loader

Fabric

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by isXander** [comment]
TIAS
