### ISSUE TITLE
[Patch Request] MC-90683 "Received unknown passenger" - Entities with differing render distances as passengers outputs error

### ISSUE THREAD

**Issue by SteveKunG** [isXander/Debugify#101]
### Mojang Bug Report ID

https://bugs.mojang.com/browse/MC-90683

### Mod Loader

N/A

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

**Comment by HyperSoop** [comment]
Hello hypixel

**Comment by Titaniumtown** [comment]
> Hello hypixel

huh?

**Comment by isXander** [comment]
I have looked into this and I can see the fact there is no checks before sending the packet.

However I cannot find what check I should implement to check if the player is tracking a certain entity.
