### ISSUE TITLE
[Patch Request] MC-174884 and MC-95782

### ISSUE THREAD

**Issue by dalekfan** [isXander/Debugify#103]
### Mojang Bug Report ID

MC-174884 and MC-95782. Both are present in 1.19 and is reproducible through keeping a iron golem close to any mob it normally attacks while both are on the same team. Other one just spawn a wither skeleton next to a piglin on the same team as it. Though I doubt you'll care according to your guidelines about issues that have been open and unfixed for a long time, which may I add, is REALLY petty.

### Mod Loader

N/A. This happens in forge, fabric, and vanilla. That's how bad it is.

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines. And then got really ticked off at the fact you can't bring yourself to fix a bug in the more recent versions of the game just cause it's old and neglected. Like you don't NEED to go all the way back to 1.12.2, dude.

### Has not already been requested.

- [X] I am certain this patch has not already been requested. I checked your entire github for it.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod. I tested it with your mod installed and working.

**Comment by isXander** [comment]
The reason I don't fix bugs that are intentionally ignored by Mojang is just that. Debugify fixes the bugs that Mojang don't have enough time for (with a few exceptions)

**Comment by dalekfan** [comment]
> The reason I don't fix bugs that are intentionally ignored by Mojang is just that. Debugify fixes the bugs that Mojang don't have enough time for (with a few exceptions)

And a small AI bug that's still present on two Nether Update mobs and iron golems is somehow not a issue that could be considered that just because it's old?
