### ISSUE TITLE
[Bug] MC-26757 fix does not appear to account for if text has many lines or if there is too much text

### ISSUE THREAD

**Issue by mattp12** [isXander/Debugify#106]
### Bug Description

The MC-26757 fix fixes text going off-screen. However, it does not seem to fix situations in which there are many new lines or if there is too much text.

An example of a command you can run to get many new lines:

`/give @p ice{display:{Lore:['{"text":"a"}','{"text":"b"}','{"text":"c"}','{"text":"d"}','{"text":"e"}','{"text":"f"}','{"text":"g"}','{"text":"h"}','{"text":"i"}','{"text":"j"}','{"text":"k"}','{"text":"l"}','{"text":"m"}','{"text":"n"}','{"text":"o"}','{"text":"p"}','{"text":"q"}','{"text":"r"}','{"text":"s"}','{"text":"t"}','{"text":"u"}','{"text":"v"}','{"text":"w"}','{"text":"x"}','{"text":"y"}','{"text":"z"}']}} 1`

![Screenshot_1](https://user-images.githubusercontent.com/8071273/173524374-2f043623-1240-4fbe-acea-69fc058041c2.png)

Additionally, if there is too much text, the text can go off-screen if the item is placed too far to the side. I believe a solution would be to wrap the text if it goes on too long.

`/give @p ice{display:{Lore:['{"text":"abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz"}']}} 1`

![Screenshot_2](https://user-images.githubusercontent.com/8071273/173525357-51a18ccf-a835-4d8f-a15f-53d68e08bad9.png)

### How to Reproduce?

Run commands from bug description and observe results.

### Expected Behavior

For the item descriptions to not go off-screen.

### Version

2.0.0

### Mod Loader Version

1.19 0.14.7

### Mod Loader

Fabric

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by isXander** [comment]
I improved behaviour vertically to try to fit the tooltip on the screen unless it goes off the top.
![image](https://user-images.githubusercontent.com/43245524/174121453-a7c29e9c-ffff-48a5-9c96-46d82970c25b.png)

**Comment by isXander** [comment]
I have also now improved behaviour horizontally by doing the same thing. If the tooltip goes off the screen to the left too much it caps it so you can always read the first bit.
![image](https://user-images.githubusercontent.com/43245524/174122740-74512321-5726-413f-b9c9-d17b3255ac0b.png)

**Comment by isXander** [comment]
Text wrapping is something I really want to avoid because
1. it's really hard to get right
2. in some cases a mod or server could utilise this issue

So I think is will suffice for now.
