### ISSUE TITLE
[Patch Request] MC-179629

### ISSUE THREAD

**Issue by MiFliK** [isXander/Debugify#111]
### Mojang Bug Report ID

MC-179629

### Mod Loader

N/A

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

**Comment by isXander** [comment]
I'm sorry but cloud rendering is too complex for me to understand ...
