### ISSUE TITLE
[Bug] Incompatibility with GoogleChat

### ISSUE THREAD

**Issue by craftish37** [isXander/Debugify#114]
### Bug Description

Game crashes on startup with bot Debugify and [GoogleChat](https://modrinth.com/mod/google-chat)

### How to Reproduce?

Install latest version of fabric or quilt in 1.18.2
Setup mods in folder
Launch
Constat the crash

### Expected Behavior

Theorically, the game should start with both mods 🤔

### Version

1.11.0

### Mod Loader Version

1.18.2 - fabric 0.56.0/QuiltMC 0.17.1 beta2

### Mod Loader

Fabric, Quilt

### Logs or additional context

[Logs](https://github.com/isXander/Debugify/files/8931255/latest.log) right here
[GitLab page](https://gitlab.com/jfmods/googlechat/-/issues/4) of GoogleChat

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by JFronny** [comment]
I cannot reproduce this using a newly created 1.18.2 profile using the latest versions of Fabric Loader, Debugify and GoogleChat (with all dependencies)
![image](https://user-images.githubusercontent.com/33260128/174441729-93675935-efd8-4f52-a99f-1b3e799d1d06.png)
@craftish37 likely didn't install an updated LibJF version, which is required for compatibility between GoogleChat and the latest fabric loader versions.
