### ISSUE TITLE
[Patch Request] MC-132067 (bubble_pop)

### ISSUE THREAD

**Issue by Shad0wolf0** [isXander/Debugify#116]
### Mojang Bug Report ID

[MC-132067](https://bugs.mojang.com/browse/MC-132067)

### Mod Loader

N/A

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

**Comment by isXander** [comment]
I don't see a way to find out when the bubbles despawn at the top...

**Comment by Andrew6rant** [comment]
https://modrinth.com/mod/make_bubbles_pop fixes MC-132067

**Comment by RaptaG** [comment]
@isXander could you consider actually adding this to Debugify, https://github.com/Tschipcraft/fabric_make_bubbles_pop_mod is open source you could take inspiration for an implementation
