### ISSUE TITLE
[Bug] Crash at launch with modpack

### ISSUE THREAD

**Issue by fabmm** [isXander/Debugify#117]
### Bug Description

Crash at launch with error

### Version

1.10.0

### Mod Loader Version

1.18.2 - 40.1.31

### Mod Loader

Forge

### Logs or additional context

https://paste.ee/p/yB2pc

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by isXander** [comment]
Caused by Selene. Report bug there
