### ISSUE TITLE
[Bug] Player collision is disabled on servers

### ISSUE THREAD

**Issue by Madis0** [isXander/Debugify#119]
### Bug Description

Installing Debugify somehow affects the player collision on an external server.

### How to Reproduce?

1. Install Debugify
2. Join a server
3. Try to collide with others 

### Expected Behavior

Cannot collide for some reason. Other players on the same server that do not use Debugify can collide.

### Version

1.11.0

### Mod Loader Version

1.18.2 - 0.14.8

### Mod Loader

Fabric

### Logs or additional context

[Thread on FO](https://discord.com/channels/859124104644788234/859124571005648946/995079934110347294)
Note that the user did not install FO configs so they got all default Debugify bugfixes.

[Forced crash](https://bytebin.lucko.me/Dg2cyJybMU)
[Launcher logs](https://bytebin.lucko.me/L1x3YOksGZ)

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by isXander** [comment]
Can confirm.
