### ISSUE TITLE
[Bug] MC-577 fix is not working properly

### ISSUE THREAD

**Issue by RaptaG** [isXander/Debugify#121]
### Bug Description

My `Drop Item` button is the <kbd>Button 5</kbd> of my mouse. When I open the inventory and press this button the items don’t drop, like in vanilla.

### How to Reproduce?

1. Remap your `Drop Item` button to the <kbd>Button 5</kbd> of your mouse (it’s a side button available for gaming mice)
2. Open your inventory and hover your cursor above an item
3. Hit the button (nothing happens)

### Expected Behavior

The items should drop

### Version

2.2.0

### Mod Loader Version

1.19 - 0.14.8

### Mod Loader

Fabric

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by isXander** [comment]
This has nothing to do with this bug fix. This has nothing to do with dropping items, but closing inventory.

**Comment by RaptaG** [comment]
Wrong. As the description says, it affect _all_ the mouse button used in the inventory, including <kbd>Drop Selected Item</kbd>:
> ## How to reproduce
>
>   1. Rebind Attack/Destroy to any unused button.
>   2. Rebind Drop Selected Items to the mouse button.
>   3. Try to use this button.
>    → It drops items as expected
>    4. Open your inventory and try to use the button.
>    → It won't drop any items

Please consider fixing that as well @isXander , it's a really annoying bug.
