### ISSUE TITLE
[Bug] MC-199467 fix introduces camera and control deviations

### ISSUE THREAD

**Issue by mrEDitor** [isXander/Debugify#122]
### Bug Description

I'm playing Minecraft 1.18.2 via Steam translation, and it emulates mouse not very accurate. When MC-199467 fix is applied with Debugify, in some circumstances it makes camera deviate and look from player's back or shoulder (i.e. when I place blocks, they are placed behind me, controls are inverted or rotated, etc.). Seems like it may be fixed in two ways, either via disabling the fix MC-199467 for Debugify or via disabling "Raw control" for mouse events (Vanilla Minecraft option, I suppose).

Not sure, is it major problem of the mod or fix itself, just hope if someone will have similar issue, they can came across the issue with google, for instance.

### How to Reproduce?

Easiest way: run Minecraft via Steam translation, hold inventory key [default E], quickly move the mouse around the screen for several seconds.
Random reproduction way: open the inventory, do something with mouse, close it. By chance, controls and camera are deviated.

### Version

1.11.0

### Mod Loader Version

0.13.3

### Mod Loader

Fabric

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by mrEDitor** [comment]
But looking at [the fix mixin](https://github.com/isXander/Debugify/blob/ee90a2eab26b1c9d2481a7282320773fd697f884/common/src/main/java/dev/isxander/debugify/mixins/basic/server/mc199467/MathHelperMixin.java#L22), I'm really sure it is completely broken. Shouldn't you use mod `2 * Math.PI` instead of 360 for radians normalization?

**Comment by isXander** [comment]
I'm not sure what steam translations is.

**Comment by mrEDitor** [comment]
My fault. I suppose it's actually called Steam Remote Playhttps://help.steampowered.com/en/faqs/view/0689-74B8-92AC-10F210:30, 17 июля 2022 г., Xander ***@***.***>:
I'm not sure what steam translations is.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by isXander** [comment]
Steam remote play wouldn't cause this. Maybe the 2PI would though.

**Comment by isXander** [comment]
Does this resolve your issue? 
https://github.com/isXander/Debugify/actions/runs/2684913697
