### ISSUE TITLE
Crash Before Loading Screen with 2.3.0[Bug] Summary of bug

### ISSUE THREAD

**Issue by digitaltrucker** [isXander/Debugify#123]
### Bug Description

I'm using GDLauncher.  With the latest version of Debugify (2.3.0) The game crashes before it gets to the loading screen, so no crash log.

Debugify 2.2.0 works fine.

### Version

2.3.0

### Mod Loader Version

0.14.8

### Mod Loader

Fabric

### Logs or additional context

latest.log - https://pastebin.com/cJ59ikmd

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by isXander** [comment]
Appears to be lithium mod conflicting.

**Comment by DuendeInexistente** [comment]
> Appears to be lithium mod conflicting.

Can confirm, I came here for this. Lithium and this don't like being together.

**Comment by jaredniegas** [comment]
Set MC-228976 to false in the Debugify config to fix this
