### ISSUE TITLE
[Mod Incompatability] [Forge 1.18.2][Debugify 1.11.0] Cannot unbind keys after searching for a key-bind while using Controlling mod

### ISSUE THREAD

**Issue by minerguy341** [isXander/Debugify#127]
After using the key-bind search you are unable to hit escape to either leave the menu, un-focus the search bar, or unbind a selected key-bind. Clicking or selecting a key-bind should un-focus the selected text box to fix this, or hitting escape once should first un-focus the text box then close the key-bind menu if a text box is not selected to begin with.
And yes, disabling the patch for [https://bugs.mojang.com/browse/MC-147605](MC-147605) Does fix this.

**Comment by isXander** [comment]
Duplicate of #135
