### ISSUE TITLE
[Crash] mod does not work in 1.19.1

### ISSUE THREAD

**Issue by papillo12** [isXander/Debugify#133]
### Bug Description

it is the only mod I have installed to see if it worked on its own and it does not work in the latest version of forge 1.19.1.

### How to Reproduce?

1. install the latest version of forge 1.19.1
2. install debugify in the latest version available for 1.19.1
3. start the game

### Expected Behavior

the game will not open because it crashes

### Version

debugify-2.3.3-forge-1.19.1.jar

### Mod Loader Version

1.19.1  42.0.1

### Mod Loader

Forge

### Logs or additional context

[latest.log](https://github.com/isXander/Debugify/files/9221468/latest.log)

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by Jaedubu** [comment]
Hello, may I ask if is there any fix to this? Thanks!

**Comment by MicrocontrollersDev** [comment]
forge support was dropped in https://github.com/isXander/Debugify/commit/768ec467078f04691c9e65ce6cea1e1547c58a62, only fabric and quilt are supported now
