### ISSUE TITLE
[Bug] MC-22882: While in the player inventory, CTRL-Q only drops one item

### ISSUE THREAD

**Issue by klutzies** [isXander/Debugify#138]
### Bug Description

Pressing CTRL+Q to drop a stack of items you're hovering over while inside the player inventory only drops one item from that stack.

### How to Reproduce?

1. Enter the player inventory (by pressing "E")
2. Hover over a stack of more than one item
3. Press CTRL+Q
4. Only one item is dropped.

### Expected Behavior

The entire stack of items is dropped.

### Version

2.4.0

### Fabric/Quilt Loader Version

0.14.8 for 1.19.1

### Logs or additional context

Debugify's patch for [MC-22882](https://bugs.mojang.com/browse/MC-22882) works fine for dropping stacks of items from the hotbar while outside of an inventory.

[Ctrl+Q](https://github.com/Mrredstone5230/Ctrl-Q) handles this properly. ~~However, it doesn't support dropping multiple stacks sequentially by holding CTRL+Q while hovering the cursor over those stacks *in non-player inventories specifically (chests, furnaces, etc.)* - a bug similar to this one. See here: https://github.com/Mrredstone5230/Ctrl-Q/issues/2~~
EDIT: That's not actually a bug in vanilla Minecraft, as pointed out in the linked issue.

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
I can't really test this because I don't have a Mac, but as far as I can tell from the code, there is no way this is possible. This must be vanilla behaviour.

**Comment by Mrredstone5230** [comment]
This is indeed Vanilla behaviour that works on either Mac or Windows. Although, I was able to make a fix for it.

**Comment by akemin-dayo** [comment]
I can confirm that this bug is occurring on macOS. Ctrl-Q (the mod) indeed handles Ctrl-Q events while in an inventory correctly, matching vanilla behaviour on Windows.

※ The "holding Ctrl-Q" functionality referred in the "additional context" section is non-vanilla behaviour added by Ctrl-Q (mod) and is not an issue with Debugify.

**Comment by isXander** [comment]
In this case, I will close, as this is the intended vanilla behaviour. In the next version, Debugify will recognise Ctrl-Q mod and disable the fix automatically, so the two mods can be used together for the non-vanilla functionality.

**Comment by isXander** [comment]
Found that it is indeed considered a bug, ([MC-135973](https://bugs.mojang.com/browse/MC-135973)). And will be tracked on #164
