### ISSUE TITLE
[Patch Request] MC-249973

### ISSUE THREAD

**Issue by Qonsyuma** [isXander/Debugify#139]
### Mojang Bug Report ID

MC-249973

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

**Comment by isXander** [comment]
It's resolved?

**Comment by isXander** [comment]
That's their problem. Chat reporting shouldn't be an issue if there is nothing to be reported.

**Comment by RayDeeUx** [comment]
> Chat reporting shouldn't be an issue if there is nothing to be reported.

Correction:
> Chat reporting shouldn't be an issue if there is nothing **being sent**.
