### ISSUE TITLE
[Bug] MC-147605 breaks text fields

### ISSUE THREAD

**Issue by crcabanillas** [isXander/Debugify#140]
### Bug Description

Noticed with JEI in particular when searching for anything with an E in the word. This would close your inventory and exit you out of JEI. In addition this fix disabled being able to click on the screen to exit a search field which would affect the Controlling mod.

### How to Reproduce?

1. bind open/close inventory to E
2. search in JEI for any term with an E

Additionally, enter any text field (JEI, Controlling) and you will be unable to click to deselect the text field, the only way to exit would be via ESC which closes the entire interface, of course.

### Expected Behavior

Typing in text fields should not affect other aspects of the game bound to typed keys. Clicking outside of a text field should end input in a text field.

### Version

1.11.0

### Fabric/Quilt Loader Version

Forge 40.1.51, Minecraft 1.18.2

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
Already fixed in 2.something

**Comment by Proxwian** [comment]
Please fix also in 1.18.2
