### ISSUE TITLE
[Patch Request] MC-202355 - Damage screen tilt is de-synced, defaulting to tilt left

### ISSUE THREAD

**Issue by Eonzenex** [isXander/Debugify#142]
### Mojang Bug Report ID

MC-202355

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

### Existing implementation

https://www.curseforge.com/minecraft/mc-mods/damage-tilt

**Comment by Eonzenex** [comment]
Video overview of the bug: [https://youtu.be/pAJPc71YOnY](https://youtu.be/pAJPc71YOnY)

**Comment by isXander** [comment]
I'm going to say this doesn't adhere to the guidelines tbh. It was a feature, now it isn't and Mojang isn't adding it back. You can use damage tilt if you want.

**Comment by Eonzenex** [comment]
😉 
https://youtu.be/wF1DPtyyF1U?t=460
