### ISSUE TITLE
[Patch Request] MC-45838

### ISSUE THREAD

**Issue by MSandro** [isXander/Debugify#143]
### Mojang Bug Report ID

MC-45838 MC-131665

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

**Comment by MicrocontrollersDev** [comment]
this was already fixed in 1.19 pre-1 no?

**Comment by MSandro** [comment]
True but not in 1,18,2 as i know :(

**Comment by isXander** [comment]
I don't support old versions
