### ISSUE TITLE
[Patch Request] MC-192420 Iron bars Z-fight on the bottom and top

### ISSUE THREAD

**Issue by lostopkk** [isXander/Debugify#147]
### Mojang Bug Report ID

MC-192420

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

**Comment by isXander** [comment]
Unfortunately this is down to a texture issue, making it out of scope for Debugify, feel free to use VanillaTweaks pack that can fix this.
