### ISSUE TITLE
Prefer bug titles in options

### ISSUE THREAD

**Issue by Madis0** [isXander/Debugify#154]
It's nice to have options for each bug, but unless you're a big Jira fan, it is not very usable.

I suggest showing the titles on the buttons as soon as they are downloaded, otherwise show the bug IDs (e.g. if the player launches it offline). Once names are downloaded bug IDs would move to tooltips.

Alternatively, some kind of combination of the two, like
`Bug name - Bug ID` in the button and
```
Bug name
Bug ID
```
in the tooltip.

That would maximize the screen real-estate usage if it fits, otherwise allow users to see the full title in the tooltip.

**Comment by isXander** [comment]
In my opinion, this would make the GUI look very messy, it doesn't really speed things up either because all you have to do is hover over to see exactly what it is.

At any sane GUI scale, none of the names fit in like this, because Mojira titles aren't designed to be small!

![480p scale 2](https://user-images.githubusercontent.com/43245524/192054153-0581f67c-358a-4a82-8aa8-d017abc06c0e.png)
![1080p scale 2](https://user-images.githubusercontent.com/43245524/192054276-b8e5b4cc-70fe-43b7-8e52-c43dfdb285fe.png)

**Comment by Madis0** [comment]
How much would it fit if the ID came after the name?

**Comment by isXander** [comment]
![image](https://user-images.githubusercontent.com/43245524/192056723-f2f7582c-0452-4acb-ae8c-40944aabb291.png)
![image](https://user-images.githubusercontent.com/43245524/192056846-215a8bfa-5b56-4c7f-b7c0-7b9a2176ebdd.png)

**Comment by Madis0** [comment]
Well, there isn't really a consistency in the naming scheme but it does look more helpful even in the smaller GUI scale.

**Comment by isXander** [comment]
I wouldn't agree, you can read the first couple of words, then you need to hover anyway to see what it does. Maybe post in #devlog in FO and see what other people think.

**Comment by Madis0** [comment]
I now remembered one thing YACL has - search. So even if bug numbers are preferred, including the title after them would make them searchable and then it wouldn't matter how much of the title is seen as people use keywords anyway. 

So I agree with Imzxhir now.

**Comment by osfanbuff63** [comment]
Honestly, since @mojira titles are supposed to give as much information as possible but in one line, I don't really think this is a good move to display it in the config option - but I believe potentially in a tooltip would be the best option. Ideally, the tooltip with be configurable too.

**Comment by isXander** [comment]
> Honestly, since @mojira titles are supposed to give as much information as possible but in one line, I don't really think this is a good move to display it in the config option - but I believe potentially in a tooltip would be the best option. Ideally, the tooltip with be configurable too.

I'm not quite sure what you mean? Tooltips already exist.

**Comment by isXander** [comment]
I could make tooltips be searchable.

**Comment by Madis0** [comment]
> > > I now remembered one thing YACL has - search. So even if bug numbers are preferred, including the title after them would make them searchable and then it wouldn't matter how much of the title is seen as people use keywords anyway.
> > > Therefore, I agree with Imzxhir now.
> > 
> > 
> > I could make tooltips be searchable.
> 
> Is there a way you can make the title of the bug or the actual bug searchable (not Bug ID)? This is similar to your idea of searchable tooltips

Bug ID should definitely be searchable as well. Imagine the cache use if the bug's contents were cached though... no thanks.

**Comment by isXander** [comment]
Bug descriptions have been searchable for quite a while now. I think this is a great solution.
