### ISSUE TITLE
[Patch Request] MC-190836, MC-176240

### ISSUE THREAD

**Issue by leonpano2006** [isXander/Debugify#158]
### Mojang Bug Report ID

MC-190836, MC-176240

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

**Comment by isXander** [comment]
Please make two individual reports!

**Comment by leonpano2006** [comment]
> Please make two individual reports!

There are the same

**Comment by leonpano2006** [comment]
> Please make two individual reports!

Please to reopen it
And there is no need to make 2 issues
Since one is duplicated (older)
