### ISSUE TITLE
[Patch Request] MC-185901 - Packets over 2MiB crash clients

### ISSUE THREAD

**Issue by AdminHcat** [isXander/Debugify#160]
### Mojang Bug Report ID

MC-185901

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

### Existing implementation

https://github.com/Tfarcenim/XLPackets

![image](https://user-images.githubusercontent.com/50044729/192235658-71bb3fe3-63d8-43f6-a553-fddd15c0b601.png)

**Comment by isXander** [comment]
There is a fundamental issue with this problem. How much data do you want to receive? This mod increases the limit to **2 GIGABYTES PER PACKET**. This seems quite large. Maybe increase it to something more reasonable like 10 mebibytes? (increased from 2 mebibytes). Or alternatively, don't kick yourself from the server? Could cause issues with chunks not loading (better than a kick?). I'd like some feedback on this.

**Comment by isXander** [comment]
Or, maybe this isn't the fault of the client at all and the server should have a better protocol for sending these large packets. (Splitting them up into smaller pieces?)

**Comment by isXander** [comment]
Going ahead and closing as this is a protocol error, which I can't change and XL Packets is not a viable fix.
