### ISSUE TITLE
MC-80859 Fix Doesn't work anymore

### ISSUE THREAD

**Issue by RayBird99** [isXander/Debugify#162]
### Bug Description

After a New update the bug for Starting to drag item stacks over other compatible stacks makes the latter invisible until appearance change (stack size increases) Doesn't fix the issue

### How to Reproduce?

Enable the fix and notice it doesn't do anything anymore

### Expected Behavior

The bug gets fixed (what would happen prior to 2.6.0)

### Version

2.7.1

### Fabric/Quilt Loader Version

0.14.9 for 1.19.2

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
Does the latest action resolve the issue for you? If not, reopen.

**Comment by RayBird99** [comment]
The issue is still present in the latest version

**Comment by RayBird99** [comment]
I can't re-open the issue unless i'm the one who closed it.
