### ISSUE TITLE
[Bug] MC-26757 (tooltipfix) displays incorrectly in some conditions

### ISSUE THREAD

**Issue by Imzxhir** [isXander/Debugify#166]
### Bug Description

Their is a tooltip even though I'm hovering over an item and their isn't supposed to be a tooltip:

![Screenshot 1](https://user-images.githubusercontent.com/98621617/193478996-7d36b024-5e7b-4826-879e-84b440f466b9.png)

This doesn't happen with ToolTipFix as you can see here:

![image](https://user-images.githubusercontent.com/98621617/193479187-b77cf5ca-71f2-415d-b7f3-7567673b9d57.png)

### How to Reproduce?

1. Go on the server 'MCC Island' (if you have a ticket)
2. Make sure you have the bug 'MC-26757' enabled
3. Go to Personal Menu
4. You've found the bug!

### Expected Behavior

There isn't supposed to be a tooltip when I'm hovering over that menu.

### Version

2.7.1

### Fabric/Quilt Loader Version

0.14.9 for 1.19.2

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
As I can't access MCC Island, I can't repeat this, could you somehow replicate it in singleplayer?

**Comment by osfanbuff63** [comment]
![2022-10-04_12 03 25](https://user-images.githubusercontent.com/91388253/193869204-277b8f9b-56b9-49cb-b458-add33752f7a9.png)
![2022-10-04_12 03 29](https://user-images.githubusercontent.com/91388253/193869276-d29751df-7faf-4a14-aef5-8f0faab047c2.png)

I can confirm this - I would imagine that it works on any server that uses custom GUIs, but I haven't tested it on any server than isn't MCCI.

**Comment by FayneAldan** [comment]
Can confirm as well. I wonder if there's some check in vanilla that prevents a tooltip from appearing if the text is just spaces and Debugify might be conflicting with that?

**Comment by FayneAldan** [comment]
Hmm. I did random testing and installed a mod that lets me see NBT data on the tooltip of an item.
Screenshot is without the Debugify fix enabled:
![image](https://user-images.githubusercontent.com/1149870/194159544-a4f366fb-db11-4c43-aad2-a1ef261a06fb.png)
So, somehow MCCI is just making *this* item (which actually makes up the background of the UI) have an invisible tooltip *background*? So, how is Debugify conflicting with this?

**Comment by isXander** [comment]
It may have something to do with tooltip data, I'll have a look.

**Comment by isXander** [comment]
This bug report should be re-filed under isXander/AdaptiveTooltips if it is still a problem as MC-26757 fix has been moved to that mod.
