### ISSUE TITLE
[Bug] MC-227169 is not fixed and is not in the config options

### ISSUE THREAD

**Issue by DreamStanMan** [isXander/Debugify#167]
![2022-10-13_23 17 52](https://user-images.githubusercontent.com/19875208/195754521-1ac007e6-7c1b-4c12-8402-7f2264430a61.png)
### Bug Description

The MC-227169 bug was supposedly fixed in Debugify, however there is no option in the config to enable/disable this fix, and hasn't been fixed.

### Version

2.7.1

### Fabric/Quilt Loader Version

0.14.9 for 1.19.1

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [x] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
This is because it has been committed to the repo but has not yet been released.

**Comment by DreamStanMan** [comment]
There is no reason to not have it planned considering it was already possible. At least remove it from the Patched bugs list, as it is not patched.

**Comment by isXander** [comment]
Look at my comment.....

**Comment by DreamStanMan** [comment]
When will it be added to Debugify? Is there an estimated time, like in your next update?
