### ISSUE TITLE
[Bug] JEI search field broken with MC-147605

### ISSUE THREAD

**Issue by Psychodeus** [isXander/Debugify#169]
### Bug Description

https://github.com/mezz/JustEnoughItems/issues/3016

### Version

2.7.1

### Fabric/Quilt Loader Version

0.14.9

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by Snowgods** [comment]
Verified this bug exists of forge version as well.
seems to push keypresses to the main window when typing in JEI search field, so that when you push 'e' it closes the inventory

**Comment by isXander** [comment]
MC-147605 is no longer a problem in the game and Debugify's fix has been removed.

**Comment by mrbuilder1961** [comment]
so why exactly is this not going to be fixed? i still have this issue with version 2.8.0, 1.19.2.

**Comment by MicrocontrollersDev** [comment]
> so why exactly is this not going to be fixed? i still have this issue with version 2.8.0, 1.19.2.

debugify doesnt support older mc versions
