### ISSUE TITLE
[info] multiplayer gameplay

### ISSUE THREAD

**Issue by rafalohaki** [isXander/Debugify#175]
gameplay_fixes_in_multiplayer
Couldnt find any info about this one. Does it enable Server Side (Both) patches?

**Comment by rafalohaki** [comment]
ps. i found a problem using debugify. i addded debugify and its breaking search function in refined storage. cant use esc to close seach bar in crafting grid.

**Comment by isXander** [comment]
Please ask for information in my discord server. GitHub is not for these types of things.
