### ISSUE TITLE
[Bug] Debugify not showing 'already fixed by the mod Adaptive Tooltips'

### ISSUE THREAD

**Issue by Imzxhir** [isXander/Debugify#176]
### Bug Description

The bug 'MC-26757' is not showing 'MC-26757 is already fixed by the mod 'Adaptive Tooltips'

### How to Reproduce?

1. Load Minecraft with Debugify and Adaptive Tooltips
2. Go to Debugify Configuration
3. Select Client Fixes
4. Find 'MC-26757'
5. You've found the bug!

### Expected Behavior

Show in the tooltip 'MC-26757 is already fixed by the mod 'Adaptive Tooltips'

### Version

2.8.0

### Fabric/Quilt Loader Version

Quilt - 0.17.6 for 1.19.2

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
Seeing as this fix was removed in 1.19.3+1.0, I am going to close this as completed. As the issue never happens anymore.
