### ISSUE TITLE
[Bug] Can't unbind keys using Esc like in Vanilla

### ISSUE THREAD

**Issue by Delfite** [isXander/Debugify#178]
### Bug Description

Whenever I try to unbind a key in the Controls menu, it doesn't work. Instead, the key stays bound and can only be rebound to another button on your keyboard. How annoying...

### How to Reproduce?

1. Install Debugify
2. Go to Options>Controls>Key Binds...
3. Click on any already-bound key
4. Press the "Esc" key to try and unbind it

### Expected Behavior

The key you attempt to unbind should've unbound itself like in Vanilla MC.

### Version

1.11.0

### Fabric/Quilt Loader Version

Fabric 0.14.10

### Logs or additional context

Log File: https://mclo.gs/eNqVVfy

After doing a binary search of my mods folder, I eventually narrowed it down to Debugify as the mod causing this issue. I looked around on this mod's github repo and saw that it had already been supposedly "fixed". Since the issue was closed, I just decided to open a new one to hopefully get this fixed as this bug is super annoying to deal with. As a result, I have since disabled Debugify to prevent this issue from showing up until a fix for it has been released.

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by Delfite** [comment]
@isXander This is still an issue in 1.18.2 as described. Fixing this would be immensely helpful.

**Comment by isXander** [comment]
I don't support old versions of Minecraft. Does this issue occur on the latest `1.19.3+1.1`?
