### ISSUE TITLE
Wrong modrinth metadata

### ISSUE THREAD

**Issue by MattiDragon** [isXander/Debugify#182]
### Bug Description

Debugify 2.8.0 (mc 1.19.2) is marked as requiring YACL 2.0.0,which is a 1.19.3 exclusive. This broke mcimagehelper and the docker image using it: itzg/mc-image-helper#70

### How to Reproduce?

1. Go to https://modrinth.com/mod/debugify/version/2.8.0
2. Notice it's for 1.19.2
3. Notice it depends on YACL 2.0.0
4. Look at YACL and notice that 2.0.0 is for 1.19.3

### Expected Behavior

The dependency be correct 

### Version

2.8.0

### Fabric/Quilt Loader Version

Irrelevant 

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by triphora** [comment]
I have updated this myself.

**Comment by isXander** [comment]
thanks
