### ISSUE TITLE
[Bug] Debugify leaves Telemetry Data completely untranslated

### ISSUE THREAD

**Issue by Madis0** [isXander/Debugify#183]
### Bug Description

![image](https://user-images.githubusercontent.com/8611110/207124686-8846339e-b1f3-4d07-a0fe-ed95f590a1a8.png)
![image](https://user-images.githubusercontent.com/8611110/207124697-51215c63-e058-422c-a32d-d6702c96ee1a.png)

### How to Reproduce?

1. Get Debugify 1.19.3+1.0
2. Use a language other than English where you know these strings would be translated
3. Look at the views

### Expected Behavior

Expected vanilla translations, because Debugify should only inject new ones 

### Version

1.19.3+1.0

### Fabric/Quilt Loader Version

0.14.11 for 1.19.3

### Logs or additional context

Fabulously Optimized 4.6.0-alpha.5

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
This is perculiar, Debugify doesn't even have a translation key for that.

**Comment by isXander** [comment]
![java_R01XKaa4Nk](https://user-images.githubusercontent.com/43245524/207457635-4f086504-77b3-47cd-baf6-c65e3927e2b7.png)
 can't repeat. are you sure that language just doesn't have translations for the new telemtry ui?

**Comment by Madis0** [comment]
As you screenshotted, it should definitely have translations. May be a conflict with Language Reload.

**Comment by Madis0** [comment]
Caused by something else, not even Language Reload.
