### ISSUE TITLE
[Bug] crashes just exploring chests 1.19.2

### ISSUE THREAD

**Issue by papillo12** [isXander/Debugify#185]
### Bug Description

well, the game crashes randomly

### How to Reproduce?

I am not sure if it can be replicated by doing the same with chests.

### Version

2.8.0 (1.19.2)

### Fabric/Quilt Loader Version

0.14.11

### Logs or additional context

[crash-2022-12-14_16.00.42-client.txt](https://github.com/isXander/Debugify/files/10232060/crash-2022-12-14_16.00.42-client.txt)

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
How have you identified that this is a problem with Debugify?

I believe this may just be a vanilla bug as Mixin reports no mixins were found in the stacktrace.
