### ISSUE TITLE
[Bug] Skeletons don't turn into strays with debugify

### ISSUE THREAD

**Issue by kohanis** [isXander/Debugify#188]
### Bug Description

With debugify installed, skeletons no longer turns into strays from powder snow
I checked it with quilt and fabric, with 1.19.2 and 1.19.3, same

### Version

2.8.0

### Fabric/Quilt Loader Version

0.14.11 for 1.19.2

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
Could you do binary search? Half fixes off, if it still consists, remove another half, if it doesn't, add half of what you removed back, repeat. This will help you identify the broken fix.

**Comment by kohanis** [comment]
Just found time. MC-214147. When enabled, any skeleton can't be converted, not just those in leather armor

**Comment by isXander** [comment]
Seems like this bug is not a bug but intended, as Minecraft specifically overrides the `canFreeze()` method for skeletons, the method that I use to try and fix this bug. So the next version will remove this fix.
