### ISSUE TITLE
[Bug] Fix for MC-46766 breaks left mouse button input in ComputerCraft: Restitched with Polymer's computer GUI after pausing game or opening chat prompt

### ISSUE THREAD

**Issue by unilock** [isXander/Debugify#191]
### Bug Description

With the [fix for MC-46766](https://github.com/isXander/Debugify/blob/1.19.3/src/client/java/dev/isxander/debugify/client/mixins/basic/mc46766/MinecraftMixin.java) applied, the player is unable to "left-click" anywhere in the GUI of a computer from [ComputerCraft: Restitched with Polymer](https://github.com/PolymerPorts/cc-restitched) ("CC Polymer") after pausing the game or opening the chat prompt, the latter either directly (`t`) or which starting a command (`/`).

### How to Reproduce?

1. Enable Debugify's fix for MC-46766.
2. Join a server with CC Polymer installed.
3. Right-click on a computer from CC Polymer to open its GUI.
4. Left-click on the on-screen keyboard to type. It works.
5. Press ESC to pause the game.
6. Unpause the game.
7. Left-click on the on-screen keyboard. Nothing happens.

### Expected Behavior

The on-screen keyboard (and other on-screen elements) continue to respond to left-clicking as normal.

### Version

2.8.0

### Fabric/Quilt Loader Version

Quilt 0.18.1-beta.25 for 1.19.2

### Logs or additional context

This is problematic, as the in-game computer accepts direct keyboard input when `/` is used to open the chat prompt, which leads to this bug preventing interaction with the UI once the chat prompt is closed.

Right-clicking in the GUI still works. However, this is used by the mod to "hold down" keys on the on-screen keyboard (i.e. to use shortcuts like `CTRL + S`), and while this *does* type whatever key is right-clicked on into the in-game computer, held down keys can't be clicked again / "let go of" until *left*-clicked - hence the issue.

(likely) Relevant file in CC Polymer:
https://github.com/PolymerPorts/cc-restitched/blob/mc-1.19.x/polymer/src/main/java/dan200/computercraft/fabric/poly/gui/MapGui.java

CC Polymer version: [`1.101.2-polymerport.1+1.19.1`](https://github.com/PolymerPorts/cc-restitched/releases/tag/1.101.2-polymerport.1%2B1.19.1)

Screenshot of the GUI in question:

![2022-12-22_21 59 53](https://user-images.githubusercontent.com/11802133/209262238-59bb9ab5-7218-46f1-a867-a10d0edd1422.png)

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
If cc polymer is failing due to my fix they are probably using weird, hacky methods to do what they do, just consider disabling debugify's fix to resolve your problem. Maybe suggest to the developer to implement the new API I just introduced into Debugify (see #192)
