### ISSUE TITLE
[Bug] HorseExpert Incompatibility

### ISSUE THREAD

**Issue by greensad** [isXander/Debugify#203]
### Bug Description

Debugify appears to be incompatible with the mod **[HorseExpert](https://www.curseforge.com/minecraft/mc-mods/horse-expert)**. When looking at a horse with Debugify installed 'Horse Expert's' tooltips do not appear. This may be due to the tooltip behavior included in TooltipFix as disabling TooltipFix in the config fixes the issue. Issue submitted on Horse Expert's [repository](https://github.com/Fuzss/horseexpert/issues/3) as well. A check to recognize that both mods are running that disables this configuration option or some other solution would be nice as most users won't know how or bother to disable it manually.

Debugify 2.80
Forge Config API Port 4.2.10
Horse Expert 4.0.0
Puzzles Lib 4.3.12
QFAPI beta 26
Trinkets 3.4.2

### How to Reproduce?

1. Launch Minecraft with Debugify and HorseExpert (plus their required dependencies; Trinkets, QFAPI/FabricAPI, Forge Config API Port, & Puzzles Lib.
2. Load or create a world.
3. Equip monocle in head trinket slot.
4. Tame a horse.
5. Look at tamed horse.

### Expected Behavior

Horse statistics appear when crosshair is on horse indicating it's health, speed, and jump height in the form of tooltips.

### Version

2.80

### Fabric/Quilt Loader Version

QFAPI beta 26 (incompatibility has existed for at least a dozen versions though)

### Logs or additional context

https://mclo.gs/WDhKNmL

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
You haven't told me what the problematic behaviour is. Only the expected and how to reproduce. It would be helpful so I can look into the issue sooner without having access to my PC.

If you have issues about the tooltip fix, try disabling that specific bug fix in the Debugify config menu and retry.

**Comment by greensad** [comment]
> You haven't told me what the problematic behaviour is. Only the expected and how to reproduce. It would be helpful so I can look into the issue sooner without having access to my PC.
> 
> If you have issues about the tooltip fix, try disabling that specific bug fix in the Debugify config menu and retry.

Apologies I genuinely did miss some information that I hope is sufficient now. After an hour of testing it was quite late for me and I must have been complacent in my drowsiness.

**Comment by greensad** [comment]
This has been resolved on the end of the HorseExpert dev.
