### ISSUE TITLE
MC-237493 fix should replace the text array entirely

### ISSUE THREAD

**Issue by Madis0** [isXander/Debugify#208]
MC-237493 fix allows users to disable telemetry. However, it only appends the text instead of hiding the originals:

![image](https://user-images.githubusercontent.com/8611110/217300072-a1c704ab-dfcc-44f9-bc72-d8a01e6daa20.png)

The text piece circled in red should not be visible when the toggle is set to "none" to prevent confusion.

**Comment by isXander** [comment]
This is a feature and was implemented from the start, perculiarly, it only works in the development environment. Must find out why.
