### ISSUE TITLE
[Patch Request] MC-67532 - Bottom 2 rows of pixels in selected hotbar slot texture don't appear in game

### ISSUE THREAD

**Issue by MenacingPerson** [isXander/Debugify#209]
### Mojang Bug Report ID

MC-67532

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

### Existing implementation

https://modrinth.com/mod/raised

**Comment by isXander** [comment]
I did implement this, but found it to be an off-putting change. I think that this can stay it's own mod for now. I may re-visit it in the future.
