### ISSUE TITLE
[Crash-Report] Underlying issue with mod compatibility

### ISSUE THREAD

**Issue by Cixon** [isXander/Debugify#214]
### Bug Description

It appears according to the crash report, there's a mixin bug with nostalgic tweaks.

### How to Reproduce?

1. Download both [Nostalgic tweaks](https://www.curseforge.com/minecraft/mc-mods/nostalgic-tweaks/files/3962798) and [THIS](https://www.curseforge.com/minecraft/mc-mods/debugify/files/3812301) debugify
2. Run client.
3. See error.

### Version

[Forge 1.18.2] 1.11.0

### Fabric/Quilt Loader Version

FML

### Logs or additional context

crash:
[crash-2023-02-19_17.30.45-client.txt](https://github.com/isXander/Debugify/files/10778267/crash-2023-02-19_17.30.45-client.txt)

log (line 508):
[latest.log](https://github.com/isXander/Debugify/files/10778268/latest.log)

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by Cixon** [comment]
Removing the nostalgic tweaks surprisingly did not fix the issue either, just got rid of the mixins mentioned.

Here's the logs and crashes after removing Nostalgic Tweaks:

crash:
[crash-2023-02-19_17.38.57-client.txt](https://github.com/isXander/Debugify/files/10778279/crash-2023-02-19_17.38.57-client.txt)

log (line 396):
[latest.log](https://github.com/isXander/Debugify/files/10778278/latest.log)

**Comment by isXander** [comment]
You are using very old versions of Debugify. I don't support forge anymore.
