### ISSUE TITLE
[Bug] [Fabric] [1.19.2] : Ingame Config not working [Mod Menu]

### ISSUE THREAD

**Issue by SpigotDE** [isXander/Debugify#215]
### Bug Description

You cant edit / see the config with Mod Menu installed
Error in Console shown

### Version

2.8.0

### Fabric/Quilt Loader Version

0.14.14 for 1.19.2

### Logs or additional context

https://gist.github.com/SpigotDE/fd51b1ac80f4e4ac53427f3a135ec00d

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by SpigotDE** [comment]
check line 864

**Comment by isXander** [comment]
I don't support 1.19.2
