### ISSUE TITLE
not compatible with jei

### ISSUE THREAD

**Issue by wsxiya** [isXander/Debugify#216]
### Bug Description

The latest version 1.19.2fabric version used together with jei will cause the jei search box to enter text and cannot be deleted

### Version

2.8.0

### Fabric/Quilt Loader Version

1.19.2

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
I don't support old versions of Debugify.
