### ISSUE TITLE
[Bug] Crash at the start

### ISSUE THREAD

**Issue by TheButterbrotMan** [isXander/Debugify#220]
### Bug Description

When, i am trying to start my game it crashes.

### How to Reproduce?

1. Download https://beta.curseforge.com/minecraft/modpacks/dragonsreach
2. Add Debugify
3. Start game
4. ???
5. Crash

### Expected Behavior

Start up, and let me play.

### Version

1.10.0

### Fabric/Quilt Loader Version

40.2.1 for 1.18.2

### Logs or additional context

https://bytebin.lucko.me/IGjsiJshEG

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
I don't support Forge anymore.
