### ISSUE TITLE
[Patch Request] MC-250644: Linux: Custom keyboard layout options are ignored

### ISSUE THREAD

**Issue by tomprince** [isXander/Debugify#227]
### Mojang Bug Report ID

MC-250644

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

**Comment by tomprince** [comment]
This was requested in #225, but that was closed by the requester.

**Comment by isXander** [comment]
This is down to GLFW, the input library that Minecraft uses and there is no way to solve this from Java code. We will just have to wait for GLFW to hopefully update!
