### ISSUE TITLE
[Bug] Crash with MC-59810 enabled

### ISSUE THREAD

**Issue by whitebear60** [isXander/Debugify#231]
### Bug Description

When I enable the fix of MC-59810 on Debugify 1.1+, Minecraft crashes. Crashlog is attached below

### How to Reproduce?

1. Enable MC-59810 in configs
2. Start / Restart the game

### Expected Behavior

The game should load normally

### Version

1.1-2.1

### Fabric/Quilt Loader Version

Fabric 0.14.19 / Quilt 0.18.10 for Minecraft 1.19.4

### Logs or additional context

https://mclo.gs/FqygaeF

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by feisar-uk** [comment]
Same here running on Apple Mac mini M2, macOS Ventura 13.4, Temurin Java 17.0.7+7, Fabric Loader 0.14.19, Debugify 1.19.4+2.1, Minecraft 1.19.4
