### ISSUE TITLE
[Bug][1.19.2 - 2.8.0] Mod is recommending Modmenu to be installed serverside.

### ISSUE THREAD

**Issue by Terminal-Access** [isXander/Debugify#235]
### Bug Description

**Minecraft Version:** 1.19.2
**Debugify Version:** 2.8.0
Mod Loader: Fabric-loader 0.14.19

Mod is recommending that modmenu is installed server side, modmenu is a client only mod.

```
 - Mod 'Debugify' (debugify) 2.8.0 recommends any version of modmenu, which is missing!
         - You should install any version of modmenu for the optimal experience.
```

This should not be prompting the install of a client only mod in a server environment.

### How to Reproduce?

Download Latest Jar for 1.19.2 add to servers mods directory, start server and review console or log file.

You will see at the very beginning on the console/log file a recomendation from the mod to install modmenu.

### Expected Behavior

Not to be prompted to install a client only mod in to a server enviroment.

### Version

2.8.0

### Fabric/Quilt Loader Version

0.14.19

### Logs or additional context

```
 - Mod 'Debugify' (debugify) 2.8.0 recommends any version of modmenu, which is missing!
         - You should install any version of modmenu for the optimal experience.
```

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
Please just ignore the warning. This is a limitation with Fabric Loader.
