### ISSUE TITLE
[Bug] blocks dont break automaticly after the first block

### ISSUE THREAD

**Issue by DeadbushCarrot** [isXander/Debugify#247]
### Bug Description

Blocks stop breaking after the first block it kinda looks like server lag but isn't

### How to Reproduce?

Go to a survival world 
Hold your left click button on your mouse to break some blocks
And it wont after the 1st

### Expected Behavior

Expected it to kept breaking blocks 

### Version

1.20 1.1

### Fabric/Quilt Loader Version

Fabric loader V1.4.21 FAPI 8.30

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by zapteryx** [comment]
seems to be an issue with MC-165381 or MC-176559, disabled both and it works fine for me now

**Comment by Excederus** [comment]
Same issue, disabling MC-176559 was enough for me to fix it.

**Comment by lospejos** [comment]
Also same issue, disabling MC-176559 was enough for me to fix it.

**Comment by isXander** [comment]
Sorry about this. I did experience this whilst testing but thought it was a server issue!
