### ISSUE TITLE
[Bug] Windows Security detects Debugify-1.20+1.1.jar as a trojan

### ISSUE THREAD

**Issue by zapteryx** [isXander/Debugify#248]
### Bug Description

Windows Security detects Debugify-1.20+1.1.jar as Trojan:Script/Wacatac.B!ml.
![image](https://github.com/isXander/Debugify/assets/9896328/a2f50f1d-ad70-4b23-9b5f-a181f6e616cd)

### How to Reproduce?

1. Download the file
2. Windows Security detects it immediately.

### Expected Behavior

Windows Security doesn't detect it

### Version

1.20+1.1

### Fabric/Quilt Loader Version

0.14.21 for 1.20

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by bendy1234** [comment]
@zapteryx  I think windows is detecting the [fractureiser](https://github.com/fractureiser-investigation/fractureiser) virus

**Comment by zapteryx** [comment]
> @zapteryx I think windows is detecting the [fractureiser](https://github.com/fractureiser-investigation/fractureiser) virus

I thought so at first, but it doesn't appear to be that. I think it's just that the jarfile is new, so it's probably a false positive. The code changes doesn't seem to have anything suspicious.
I've also checked the jarfile against the jar infection scanner provided on the CurseForge support article, and it didn't come up as a virus.

**Comment by isXander** [comment]
Lots of mods by me and other mod creators have been flagged for this particular trojan. **This is a false positive** and **you are safe** to continue to use my mods. I was completely unaffected by fractureiser.

Notice the flag is called `Trojan:Script/Wacatac.B!ml` where `!ml` stands for *machine learning*.
