### ISSUE TITLE
[Bug] Impossible to join serveur with 1.20.1

### ISSUE THREAD

**Issue by NoltoxGit** [isXander/Debugify#253]
### Bug Description

Hello!
I updated all my mods on my instance, so Debugify, and after deactivating all my mods to find the culprit, and Debugify is the problem. It's impossible to join a multiplayer server with the latest version. 

### Version

1.20.1+1.0

### Fabric/Quilt Loader Version

0.14.21

### Logs or additional context

Logs : https://mclo.gs/qE0TFpi

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by OldWorldOrdr** [comment]
I also have this issue

**Comment by Shrek616** [comment]
also

**Comment by OldWorldOrdr** [comment]
fixed in latest update
