### ISSUE TITLE
[Bug] Impossible to join a single player world in 1.20.1

### ISSUE THREAD

**Issue by 31j** [isXander/Debugify#254]
### Bug Description

I updated my mods in my instances (Prism Launcher on Fedora Linux) and narrowed it down to Debugify. Attached is a log (with only debugify and fabric api). 

### How to Reproduce?

1. Launch a single player world
2. Gets stuck on 100% 

### Expected Behavior

Single player worlds should load

### Version

1.20.1-1.0

### Fabric/Quilt Loader Version

0.14.21

### Logs or additional context

Log can be found here https://mclo.gs/P1ffB3k

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by Shrek616** [comment]
also

**Comment by Cookie-Kurokami** [comment]
I can confirm that I've been experiencing the same problem.

**Comment by ItzSkyReed** [comment]
The same

**Comment by 31j** [comment]
This issue could not be replicated with Prism Launcher on Windows 11, specifically the Fabulously Optimized pack which embeds the 1.20.1-1.0 version of Debugify. If you require further testing on this version it will take me some time as it is a friend's computer, but I can test on Windows 10 if needed.

**Comment by 31j** [comment]
My apologies, this appears to be a dupe of #252, I don't think it's a dupe of #253 but they could very well be related.
