### ISSUE TITLE
[Bug] MC-176559 causing malformed mining

### ISSUE THREAD

**Issue by needvoid** [isXander/Debugify#256]
### Bug Description

When switching mining targets mid break, the animation and client-side block break still happens on the initial block, and does not break the block server side.

### How to Reproduce?

1. Be on 1.20+ Fabric.
2. Enable MC-176559 bug patch.
3. Mine one block and switch to another before the block breaking as finished.

### Expected Behavior

The target block should change upon looking at a different target block (like normal Minecraft), but does not.

### Version

1.20

### Fabric/Quilt Loader Version

0.14.21

### Logs or additional context

Clip of bug:
https://cdn.discordapp.com/attachments/1118555458156896336/1118555752836120656/2023-06-14_10-00-55.mp4

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by AcidGames** [comment]
Experiencing the same issue was going through the mods i just added to figure out which was causing it glad you reported this made it easier for me to track down the culprit its not unplayable just inconvenient

**Comment by isXander** [comment]
See #251
