### ISSUE TITLE
[Bug] MC-160095 conflicts with carpet-fixes

### ISSUE THREAD

**Issue by FunkyNico** [isXander/Debugify#257]
### Bug Description

The game crash when is starting because of a mixin conflict.

### How to Reproduce?

1. Install Debugify-1.20.1+1.1 and Carpet Fixes.
2. Start the game.
3. Die.

### Expected Behavior

The game start correctly.

### Version

1.20.1+1.1

### Fabric/Quilt Loader Version

Fabric 0.14.21 for 1.20.1

### Logs or additional context

[Link to log file](https://mclo.gs/DdUZNRv)

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
Thanks for the report!
This is due to MC-160095 bugfix conflicting with carpet-fixes. In future versions, I will mark this fix as incompatible. For now, you can disable this through settings while temporarily disabling carpet fixes so you can get to the error gui.

**Comment by FunkyNico** [comment]
I can confirm this was the issue, i fixed it disabling the fix on the config of debugify and then activate the carpet-fixes again.
