### ISSUE TITLE
[Blocks] Can't Continue Breaking Blocks After Breaking One

### ISSUE THREAD

**Issue by dexula** [isXander/Debugify#258]
### Bug Description

Video Link:
https://medal.tv/games/minecraft/clips/1euD9ccN2j_tkc/d1337oxOWhEV?invite=cr-MSw5REwsNDI0MDg2Mzcs

### How to Reproduce?

1. Hold left click to break block.
2. Continue Breaking Blocks.
3. Blocks won't break

### Expected Behavior

Continue breaking blocks

### Version

1.20

### Fabric/Quilt Loader Version

0.14.21 Fabric

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
Please update to 1.20.1 version of Debugify! This fixes your issue!
1.20.1 is a very minor update and all but a few mods require updating (all of which the updates have released). There is no reason to continue using 1.20.
You **CAN** join 1.20 servers on a 1.20.1 client.

**Comment by dexula** [comment]
Thank you for replying. Will updating to 1.20.1 allow my other 1.20 mods work? I use Fabric-Essential as my main source of modding just so my friends and I can play. And we've selected a whole bunch of mods prior to 1.20.1 update

**Comment by onkoe** [comment]
Thanks for the update! I found this to be an issue in my modpack, too! However, many mods for `1.20` *really* supported snapshots that were known to be stable, so they also included `1.20` in their version list - before `1.20` released! 

Now, after `1.20.1` came out, a lot of mods are still stuck on `1.20` for that silly reason..! 

It'd be incredible to get a `1.20.1` -> `1.20` "backport" of this release. I'm happy to open up a PR if you'll distribute the update to Modrinth and beyond. Please feel free to let me know if that sounds good - or if you have other plans. @isXander

**Comment by isXander** [comment]
I'd be surprised if 1.20.1 broke *any* mods whatsoever. Either add a fabric loader dependency override for Debugify or just use 1.20.1

**Comment by onkoe** [comment]
I'm sorry! I just realized that "dependency override" could be an actual feature of Fabric, [and I was right](https://fabricmc.net/wiki/tutorial:dependency_overrides). Eventually. :p 

Sorry for the misunderstanding, and thanks for the assistance with this problem!
