### ISSUE TITLE
Issues with Debugify mod in Minecraft 1.20: Block mining continuity disruption and lack of grass seed drops

### ISSUE THREAD

**Issue by YumatanGames** [isXander/Debugify#260]
### Bug Description

In my Minecraft game with a plethora of mods installed (please see the modlist below for reference), I have found out that the Debugify mod (version 1.20+1.1, for Minecraft 1.20) is causing two significant issues.

Block mining disruption: When Debugify is installed, I am unable to continuously mine blocks by keeping the left mouse button pressed. Normally, once you've finished mining one block, the next one in line starts to be mined automatically if the mouse button is kept pressed. However, with Debugify, I need to release and press the left mouse button again for every single block. This issue affects all blocks, irrespective of the tools used or even with no tools at all.

Absence of grass seed drops: While Debugify is active, grass doesn't drop seeds. I've spent hours breaking grass with no seeds dropped. When I removed Debugify, seeds began to drop again as expected.

These issues occur only in survival mode and are not observable in creative mode. As I have many mods installed and have not tested Debugify by itself, it's unclear if these are inherent bugs with Debugify or a result of conflicts with other mods. Nonetheless, it is certain that removing Debugify removes the issues.

### How to Reproduce?

Install Minecraft 1.20 with Java Version 17.0.1
Install Debugify 1.20+1.1 along with the list of mods provided below
Start a game in survival mode
Try mining multiple blocks in a row with the left mouse button kept pressed
Try breaking grass and observe the absence of seed drops

### Expected Behavior

When mining, if the left mouse button is kept pressed after mining one block, the next block in line should start being mined automatically.
Grass should drop seeds when broken.

### Version

1.20+1.1

### Fabric/Quilt Loader Version

Fabric 0.14.21

### Logs or additional context

 [✔] 3dskinlayers-fabric-1.5.3-mc1.20
  [✔] abstoneedition-2.1.0b-fabric-mc1.20
  [✔] abverticaledition-1.0.3b-fabric-mc1.20
  [✔] ACE-2.0.5
  [✔] additionallanterns-1.0.5-fabric-mc1.20
  [✔] AdditionalStructures-1.20.x-(v.4.2.0)
  [✔] additionz-1.1.10
  [✔] advancednetherite-fabric-2.0.2-1.20
  [✔] advancementinfo-1.20-fabric0.83.0-1.3.1
  [✔] advancementscreenshot-1.20.0-4.1
  [✔] adventurez-1.4.18
  [✔] AirHop-v7.0.0-1.20-Fabric
  [✔] alternate-current-mc1.20-1.6.0
  [✔] AmbientEnvironment-fabric-1.20-10.0.0.3
  [✔] AmbientSounds_FABRIC_v5.2.19_mc1.20
  [✔] amecs-1.3.9+mc.1.20-pre2
  [✔] amethyst-tools-v1.0_fabric+quilt_mc1.20.0
  [✔] animal_feeding_trough-1.0.3+1.20
  [✔] appleskin-fabric-mc1.20-2.5.0
  [✔] ArcaneLanterns-v7.0.0-1.20-Fabric
  [✔] ArchaeologyBanners-Fabric-1.20-4.0.1
  [✔] archeologyplus-1.0.1
  [✔] architectury-9.0.8-fabric
  [✔] areas-1.20.0-4.4
  [✔] armorstands-1.2.0+1.20
  [✔] ash_api-fabric-2.1.0+1.20
  [✔] autosmeltenchant-1.3.0
  [✔] axolotlbuckets-1.2.0+1.20
  [✔] azurelib-fabric-1.20-1.0.14
  [✔] badpackets-fabric-0.4.1
  [✔] balm-fabric-1.20-7.0.4
  [✔] bclib-3.0.8
  [✔] BetterAdvancements-Fabric-1.20-0.3.2.159
  [✔] BetterAnimationsCollection-v7.0.0-1.20-Fabric
  [✔] betterarcheology-1.0.1
  [✔] bettercombat-fabric-1.7.2+1.20.1
  [✔] better-enchanted-books-1.20-1.4.3
  [✔] better-end-4.0.4
  [✔] better-nether-9.0.5
  [✔] bettersafebed-fabric-1.20-8
  [✔] BetterSmithingTable-v1.0.0-Fabric-1.20
  [✔] betterthanmending-1.3.0
  [✔] BetterThirdPerson-Fabric-1.20-1.9.0
  [✔] BetterTridents-v7.0.0-1.20-Fabric
  [✔] bettertrims-1.0.1
  [✔] bettervillage-fabric-1.20.0-3.1.0
  [✔] big-extras-fabric-1.9.1+1.20
  [✔] biomemakeover-FABRIC-1.20.0-1.10.0
  [✔] biomemoss-1.1.0
  [✔] biome-sniffer-1.2-BETA+1.20
  [✔] blasting-plus-1.1
  [✔] blockus-2.7.1+1.20
  [✔] blur-3.1.0
  [✔] Bookshelf-Fabric-1.20-19.0.15
  [✔] Bovines-And-Buttercups-Fabric-1.6.1+1.20
  [✔] brrp-fabric-1.0.0-1.20.1
  [✔] c2me-fabric-mc1.20-0.2.0+alpha.10.88
  [✔] capes-1.5.2+1.20-fabric
  [✔] carpet-addons-not-found-1.20-1.2.2
  [✔] carpet-ams-addition-mc1.20-v2.0.2
  [✔] carpet-extra-1.20-1.4.115
  [✔] carpet-tis-addition-mc1.20.1-v1.48.1
  [✔] charmofundying-fabric-6.4.0+1.20.1
  [✔] cherish-1.2.0
  [✔] cherishedworlds-fabric-6.1.0+1.20.1
  [✔] CITResewn-1.1.3+1.20
  [✔] cleancut-fabric-6.0+mc1.19.1-mc1.20.x
  [✔] CleanF3-0.4.0-mc1.20
  [✔] cloth-config-11.0.99-fabric
  [✔] Clumps-fabric-1.20-11.0.0.1
  [✔] collective-1.20.0-6.57
  [✔] combatroll-fabric-1.2.1+1.20.1
  [✔] comforts-fabric-6.3.2+1.20.1
  [✔] completeconfig-2.4.0
  [✔] CompletionistsIndex-v7.0.0-1.20-Fabric
  [✔] continuebutton-1.1.1+1.20
  [✔] continuity-3.0.0-beta.2+1.20
  [✔] Controlling-fabric-1.20-12.0.2
  [✔] copperhopper-0.3.0+1.20.0
  [✔] cozy-1.1.0-fabric
  [✔] CreativeCore_FABRIC_v2.10.23_mc1.20
  [✔] CreativeOnePunch-1.3-universal
  [✔] creeperoverhaul-3.0.0-fabric
  [✔] cristellib-1.1.0
  [✔] cryingportals-1.20.0-2.3
  [✔] ctov-3.3.0
  [✔] CullLessLeaves-1.2.0
  [✔] cyclepaintings-1.20.0-3.2
  [✔] dark-loading-screen-1.6.14
  [✔] DarkPaintings-Fabric-1.20-16.0.2
  [✔] dark-waters-1.20-0.0.18
  [✔] dashloader-5.0.0-beta.1+1.20.0
  [✔] DeathFinder-v7.0.0-1.20-Fabric
  [✔] deathlog-0.3.2+1.20
  [✘] Debugify-1.20+1.1.jar (disabled)
  [✔] DeepslateInstamine_mc1.20-2.5_release-fabric
  [✔] DiagonalFences-v7.0.0-1.20-Fabric
  [✔] discarpet-1.20-1.5.0
  [✔] dragondropselytra-1.20.0-3.0
  [✔] DripSounds-1.19.4-0.3.2
  [✔] dungeons-and-taverns-v2.1.3
  [✔] dungeonz-1.0.1
  [✔] dynamiccrosshair-7.0.2+1.20-fabric
  [✔] dynamic-fps-2.4.0
  [✔] earth2java-fabric-1.10.1+1.20
  [✔] EasyAnvils-v7.0.0-1.20-Fabric
  [✔] EasyMagic-v7.0.0-1.20-Fabric
  [✔] EasyShulkerBoxes-v7.0.0-1.20-Fabric
  [✔] eating-animation-1.9.4+1.20
  [✔] EchoChest-v7.0.1-1.20-Fabric
  [✔] elytraslot-fabric-6.3.0+1.20.1
  [✔] elytratrims-1.1.7+1.20
  [✔] elytra-trims-extensions-1.0.1
  [✔] emi-1.0.3+1.20+fabric
  [✔] EnchantingInfuser-v7.0.0-1.20-Fabric
  [✔] enchantmentcompat-1.2.1+1.20
  [✔] enchantment-lore-1.3.2+MC1.20-1.20.1
  [✔] EnderZoology-v7.0.0-1.20-Fabric
  [✔] enhancermod-1.0.2-1.20.0
  [✔] entity_model_features_fabric_1.20-0.2.10
  [✔] entity_texture_features_fabric_1.20-4.4.4
  [✔] Essential-fabric_1-19
  [✔] exit-confirmation-2.4.0-mc.1.20
  [✔] exlinefurniture-fabric-1.20-v2.6.0
  [✔] experience-shards-1.1
  [✔] extendedclouds-1.2.2+1.20
  [✔] fabric-api-0.83.1+1.20.1
  [✔] fabric-carpet-1.20-1.4.112+v230608
  [✔] fabric-language-kotlin-1.9.5+kotlin.1.8.22
  [✔] fallingleaves-1.15.1+1.20.1
  [✔] ferritecore-6.0.0-fabric
  [✔] fish_of_thieves-mc1.20-v3.0.0-fabric
  [✔] fluidlogged-1.2.1-fabric-mc1.20
  [✔] fluidvoidfading-1.1.0
  [✔] food-plus-2.2+1.20.1
  [✔] ForgeConfigAPIPort-v7.0.0-1.20-Fabric
  [✔] ForgeConfigScreens-v7.0.0-1.20-Fabric
  [✔] freecam-fabric-modrinth-1.2.0+1.20
  [✔] friendsandfoes-beekeeperhut-fabric-mc1.20-1.3.0
  [✔] friendsandfoes-fabric-mc1.20-1.9.0
  [✔] friendsandfoes-flowerymooblooms-fabric-mc1.20-1.1.0
  [✔] Gamma-Utils-1.7.15-mc1.20.1
  [✔] geckolib-fabric-1.20-4.2
  [✔] geodesy-2.2
  [✔] glowing-torchflower-mc1.20-rc1-1.0.0
  [✔] Grass_Overhaul-Fabric-23.06.09_MC1.20
  [✔] graves-3.0.0-beta.2+1.20
  [✔] grind-enchantments-3.1.2+1.20
  [✔] grizzlybear-1.20-1.6
  [✔] gugle-carpet-addition-2.6.0-1.20
  [✔] HeldItemTooltips-v7.0.0-1.20-Fabric
  [✔] idemandmore-0.0.3
  [✔] IllagersWearArmor-1.1.0+1.20
  [✔] ImmediatelyFast-1.1.15+1.20.1
  [✔] immersive_aircraft-0.5.1+1.20-fabric
  [✔] immersive_paintings-0.6.1+1.20-fabric
  [✔] imst_n-1.1.0
  [✔] imst-2.1.0
  [✔] incantationem-1.2.1+1.20
  [✔] indium-1.0.18+mc1.20
  [✔] iris-mc1.20-1.6.4
  [✔] Jade-1.20-fabric-11.1.3
  [✔] krypton-0.2.3
  [✔] lambdynamiclights-2.3.1+1.20.1
  [✔] lazydfu-0.1.3
  [✔] LeaveMyBarsAlone-v7.0.0-1.20-Fabric
  [✔] LeavesBeGone-v7.0.0-1.20-Fabric
  [✔] letmedespawn-fabric-1.20-1.1.0
  [✔] libraryferret-fabric-1.20-4.0.0
  [✔] light-overlay-8.0.0
  [✔] linkart-5.1.1-1.19.3
  [✔] lithium-fabric-mc1.20-0.11.2
  [✔] logcleaner-1.0.0
  [✔] lunade-fastanim-1.6-1.20
  [✔] MagnumTorch-v7.0.0-1.20-Fabric
  [✔] mavapi-1.1.1-mc1.20
  [✔] mavm-1.2.4-mc1.20
  [✔] memoryleakfix-fabric-1.17+-1.1.1
  [✔] microcutting-1.20-rc1-1.5.0
  [✔] minecraft-comes-alive-7.5.3+1.20-universal
  [✔] mini-extras-fabric-1.8.1+1.20
  [✔] minitweaks-1.20-1.4.0
  [✔] mixintrace-1.1.1+1.17
  [✔] mob-captains-v2.1.2
  [✔] MobLassos-v7.0.0-1.20-Fabric
  [✔] mobs-attempt-parkour-0.5-1.20
  [✔] modernfix-fabric-5.0.4+mc1.20.1
  [✔] modmenu-7.0.1
  [✔] moonlight-1.20-2.5.6-fabric
  [✔] mooshroomtweaks-1.20.0-3.2
  [✔] more-axolotl-2.0.1-1.20
  [✔] morebannerfeatures-1.2.0-1.20
  [✔] MoreBows-1.0.11+1.20.x
  [✔] morediscs-1.20-28-fabric
  [✔] more-mobs-1.4
  [✔] moremobvariants-fabric+1.20-1.2.2
  [✔] mossier-deepslate-1.20-2.0.2
  [✔] mousewheelie-1.11.1+mc1.20-pre2
  [✔] MutantMonsters-v7.0.0-1.20-Fabric
  [✔] NetherChested-v7.0.1-1.20-Fabric
  [✔] netherportalfix-fabric-1.20-13.0.0
  [✔] NetherSheep-1.7-1.20-fabric
  [✔] notenoughanimations-fabric-1.6.4-mc1.20
  [✔] now-playing-fabric-1.4.3
  [✔] npc-variety-1.20-2.3.0
  [✔] nutritious-feast-1.6.1
  [✔] OverflowingBars-v7.0.0-1.20-Fabric
  [✔] OverpoweredMending-1.20-2.11.0
  [✔] owo-lib-0.11.0+1.20
  [✔] oxidized-1.8.2
  [✔] oxirods-1.20-5
  [✔] particle-rain-2.0.5
  [✔] ParticleTweaks-1.1.1-1.20
  [✔] PermanentSponges-v7.0.0-1.20-Fabric
  [✔] physics-mod-pro-v155-fabric-1.20
  [✔] PickUpNotifier-v7.0.0-1.20-Fabric
  [✔] pinglist-1.4
  [✔] player-animation-lib-fabric-1.0.2-rc1+1.20
  [✔] PlentyPlates-v7.0.0-1.20-Fabric
  [✔] PresenceFootsteps-1.9.0
  [✔] preventaging-1.1-1.19-1.20-fabric
  [✔] puzzle-1.5.1+1.20
  [✔] PuzzlesLib-v7.0.9-1.20-Fabric
  [✔] qu-enchantments-1.3.5-1.20
  [✔] radiantgear-fabric-2.1.0+1.20.1
  [✔] rainglow-1.1.1+mc1.20.1
  [✔] randomvillagenames-1.20.0-3.3
  [✔] reacharound+1.20-1.1.2
  [✔] realisticbees-1.20.0-3.4
  [✔] reeses_sodium_options-1.5.1+mc1.20-build.74
  [✔] refined-advancements-1.0.3a
  [✔] RegionsUnexploredFabric-0.4.1+1.20
  [✔] regrowth-1.20-46.31.1
  [✔] reinforced-barrels-2.4.1+1.20
  [✔] reinforced-chests-2.4.2+1.20
  [✔] reinforced-shulker-boxes-2.4.1+1.20
  [✔] renewablesporeblossoms-1.0.0
  [✔] repurposed_structures-7.0.0+1.20-fabric
  [✔] resourcefulconfig-fabric-1.20-2.0.0
  [✔] rpgdifficulty-1.3.12
  [✔] rsls-1.0.1
  [✔] ruined-equipment-2.3.1+1.20.1
  [✔] scaffoldingdropsnearby-1.20.0-3.0
  [✔] scarecrowsterritory-1.1.9-fabric-mc1.20
  [✔] seamless-1.3.0-fabric-1.19.2
  [✔] Searchables-fabric-1.20-1.0.2
  [✔] servercore-fabric-1.3.6+1.20
  [✔] sheets-1.3
  [✔] shuffle-fabric-8.1.0+1.20
  [✔] shulkerdropstwo-1.20.0-3.1
  [✔] shulkerloader-fabric-1.19.3-1.20-1.0.9
  [✔] skeletalremains-1.3.3.1.20.1
  [✔] sleepsooner-1.20.0-4.1
  [✔] smallships-fabric-1.20-2.0.0-a2.3.2
  [✔] SmartBrainLib-fabric-1.20.1-1.11.1
  [✔] smoothchunk-fabric-1.20.1-3.0
  [✔] Sniffer+-fabric-1.20.1-0.2.0
  [✔] sodium-extra-0.4.20+mc1.20-build.103
  [✔] sodium-fabric-mc1.20-0.4.10+build.27
  [✔] soundphysics-fabric-1.20-1.1.1
  [✔] spyglass_astronomy-1.0.5-mc1.20+
  [✔] starlight-1.1.2+fabric.dbc156f
  [✔] Stoneworks-v7.0.1-1.20-Fabric
  [✔] striders-grace-1.0.0+1.20
  [✔] structureessentials-fabric-1.20.1-2.9
  [✔] supermartijn642configlib-1.1.6-fabric-mc1.20
  [✔] supermartijn642corelib-1.1.9b-fabric-mc1.20
  [✔] supplementaries-1.20-2.5.8
  [✔] symbol-chat-1.20-1.0.0
  [✔] TaxFreeLevels-1.3.3-fabric-1.19
  [✔] tectonic-mod-mc1.20-v2
  [✔] TerraBlender-fabric-1.20-3.0.0.163
  [✔] The_Graveyard_2.9.1_(FABRIC)_1.20+
  [✔] TinySkeletons-v6.0.0-1.20-Fabric
  [✔] tooltipfix-1.1.1-1.20
  [✔] Towns-and-Towers-1.11-Fabric+Forge
  [✔] TradingPost-v7.0.0-1.20-Fabric
  [✔] transcendingtrident-1.20.0-4.2
  [✔] travelers-backpack-1.20-9.0.2
  [✔] treeharvester-1.20.0-8.1
  [✔] trimmable-tools-mc1.20-v1.0.4
  [✔] trinkets-3.7.0
  [✔] UniversalBoneMeal-v7.0.0-1.20-Fabric
  [✔] Variety_Aquatic-fabric-1.0.4.7
  [✔] VarietyAPI-Fabric-1.0 (1)
  [✔] veinmining-fabric-1.2.0+1.20.1
  [✔] villagernames-1.20-4.5.1
  [✔] VillagersPlus_1.11_(FABRIC)_for_1.20
  [✔] visuality-0.7.0+1.20
  [✔] VisualWorkbench-v7.0.0-1.20-Fabric
  [✔] Void-Fog-2.10.0
  [✔] voidz-1.0.9
  [✔] vorpal-enchantment-1.20-3.0.3
  [✔] waystones-fabric-1.20-14.0.0
  [✔] Weeping-Angels-46.0.1-fabric
  [✔] WilderWild-2.0.4-Fabric+1.20
  [✔] windchimes-1.2.3+1.20
  [✔] Xaeros_Minimap_23.5.0_Fabric_1.20
  [✔] XaerosWorldMap_1.30.6_Fabric_1.20
  [✔] yet-another-config-lib-fabric-3.0.1+1.20
  [✔] Zoomify-2.10.0

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by YumatanGames** [comment]
I know the bug was fixed on 1.20.1 1.0+ but this version is not compatible with 1.20, which is the Minecraft version I'm currently playing while waiting for all the mods I currently play with to also update to 1.20.1. Is it possible to release a fix for this bug, that is also compatible with 1.20? 

I would appreciate the attention! Thanks! :D

**Comment by isXander** [comment]
Please see the pinned issue #258
