### ISSUE TITLE
[Bug] Debugify asks for YACL 3.x even if 3.1.0 is present on mods folder

### ISSUE THREAD

**Issue by vico93** [isXander/Debugify#277]
### Bug Description

Basically, i got this line on my latest.log when loading a singleplayer world:

```
[13:32:45] [main/WARN]: Warnings were found!
 - Mod 'Debugify' (debugify) 1.20.1+2.0 recommends any 3.x version of yet-another-config-lib, which is missing!
	 - You should install any 3.x version of yet-another-config-lib for the optimal experience.
```

But i have `yet-another-config-lib-fabric-3.1.0+1.20.jar` on my mods folder.

Pretty minor (mods seems to work normally regardless of this line) but solving it could prevent further confusion in future unrelated issues.

### Version

2.0

### Fabric/Quilt Loader Version

Fabric 0.14.21 for 1.20.1

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by DreamSt4n** [comment]
I can confirm that this is the case. I thought this was quite weird, honestly.
