### ISSUE TITLE
[Bug] cant destory block

### ISSUE THREAD

**Issue by thelosss** [isXander/Debugify#282]
### Bug Description

when i destory first cant hold to destory another one

### Version

1.20+1.1 (1.20)

### Fabric/Quilt Loader Version

fabric-loader-0.14.22-1.20

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by isXander** [comment]
Please update debugify!
