### ISSUE TITLE
Remove missing mod menu warning for servers

### ISSUE THREAD

**Issue by nco2k** [isXander/Debugify#299]
> [main/WARN]: Warnings were found!
> - Mod 'Debugify' (debugify) 1.20.2+1.0 recommends any version of modmenu, which is missing!
> - You should install any version of modmenu for the optimal experience.

any chance you could remove that warning for servers? servers usually dont allow mod menu to be installed, because its client-only.

**Comment by isXander** [comment]
Limitation with Fabric, you can't specify environment of a dependencies.
