### ISSUE TITLE
Server crashes because of fabric resource loader v0 not present

### ISSUE THREAD

**Issue by Legendmanj** [isXander/Debugify#332]
Even though I am on a fabric 1.20.6 server, the mod debugify says it needs the fabric resource loader v0 

The only thing I understand about it is that mod itself is the fabric loader.
Please mind helping me download that mod, as I am unable to find it anywhere else. I also can't seem to understand why it is happening, as the fabric loader is already present in the server with the required fabric stuff.

Thank-you
I just want to know how and where to download the mod, why it is causing it 

ggs

**Comment by isXander** [comment]
You need Fabric API.
