### ISSUE TITLE
[Patch Request] MC-165182

### ISSUE THREAD

**Issue by Soochaehwa** [isXander/Debugify#80]
### Mojang Bug Report ID

MC-165182

### Mod Loader

N/A

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

https://bugs.mojang.com/browse/MC-165182

**Comment by isXander** [comment]
Sodium fixes this but (afaik) plans to revert fix in case of resource packs that abuse it.
