### ISSUE TITLE
[Forge] MC-234898 causing crash

### ISSUE THREAD

**Issue by border999** [isXander/Debugify#84]
### Bug Description

Crash on startup

### Version

1.10.0

### Mod Loader Version

1.18.2 - 40.1.16

### Mod Loader

Forge

### Logs or additional context

[crash-2022-05-07_19.33.26-client.txt](https://github.com/W-OVERFLOW/Debugify/files/8646144/crash-2022-05-07_19.33.26-client.txt)

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by MicrocontrollersDev** [comment]
Does disabling MC-234898 fix this? (can disable via the config file)

**Comment by border999** [comment]
As far as I'm aware, it doesn't get to the point where it looks/ alters the config. I tried deleting the config before in an attempt to fix this issue. Still crashed and when I checked the config folder the file hadn't been remade.

**Comment by Wyvest** [comment]
> As far as I'm aware, it doesn't get to the point where it looks/ alters the config. I tried deleting the config before in an attempt to fix this issue. Still crashed and when I checked the config folder the file hadn't been remade.

micro asked if disabling MC-234898 fixes the issue, not if the config screen also dies

**Comment by isXander** [comment]
Use the JSON file located at `.minecraft/config/debugify.json`

**Comment by border999** [comment]
can confirm, disabling MC-234898 fixes the issue.

**Comment by OcrSu** [comment]
i have the same problem,,disabling MC-234898 fixes the issue.

**Comment by isXander** [comment]
Fixed in next update. Removed fix
