### ISSUE TITLE
[Bug] Crash on startup (forge)

### ISSUE THREAD

**Issue by Wedge1453** [isXander/Debugify#92]
### Bug Description

using forge 40.1.0, crashed on startup, even when Debugify ois the only mod.

### Version

debugify-1.10.0-forge-1.18.2

### Mod Loader Version

40.1.0

### Mod Loader

Forge

### Logs or additional context

[crash-2022-05-29_10.30.49-client.txt](https://hst.sh/tujejaduca.pl)

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by isXander** [comment]
Disable MC-234898 fix. Will be removed in next update.
