### ISSUE TITLE
[Patch Request] MC-228976 - Entity cramming on render thread

### ISSUE THREAD

**Issue by RaptaG** [isXander/Debugify#93]
### Mojang Bug Report ID

[MC-228976](https://bugs.mojang.com/browse/MC-228976)

### Mod Loader

N/A

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

**Comment by RaptaG** [comment]
Also, this bug is fixed by [this mod](https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix-fabric) too

**Comment by isXander** [comment]
Added in 1.11.0 (unreleased)
