### ISSUE TITLE
[Bug] Invisible particles and entities

### ISSUE THREAD

**Issue by wasdspace** [isXander/Debugify#96]
### Bug Description

I swear this never happened before adding debugify, all particle effects and entities are invisible, you can see even my hand is.

![2022-06-01_22 40 53](https://user-images.githubusercontent.com/85009668/171433508-065fff81-9763-49a9-99f6-293db3f45880.png)

Most of the time restarting the game fixes it (and seems to be the only solution), but it's really annoying.

### How to Reproduce?

Probabilistic event, usually doesn't happen.

### Version

1.11.0

### Mod Loader Version

1.18.2-40.1.30

### Mod Loader

Forge

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by isXander** [comment]
Does this happen when you use Debugify by itself?

**Comment by mintynora** [comment]
this could be caused by optifine

**Comment by wasdspace** [comment]
The culprit should be [Entity Culling](https://www.curseforge.com/minecraft/mc-mods/entityculling) mod maded by tr9zw. In fact, I was using Rubidium instead of Optifine at the time of reporting this issue. I have since investigated and found that this occurs more frequently when using Optifine than using Rubidium, this may be due to the Optifine's modifications to the vanilla rendering codes are more invasive.
