### ISSUE TITLE
[Patch Request] MC-246262

### ISSUE THREAD

**Issue by HyperSoop** [isXander/Debugify#99]
### Mojang Bug Report ID

MC-246262

### Mod Loader

N/A

### Bug adhere to the guidelines.

- [x] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

**Comment by isXander** [comment]
fixed in 1.19
